<h1> Numpy</h1>

<p> numpy קודם כל נתקין את הספריה </p> 

In [3]:
pip install numpy

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     -------------------- ------------------- 30.7/60.8 kB 1.3 MB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 648.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.9 MB 3.2 MB/s eta 0:00:05
    --------------------------------------- 0.2/12.9 MB 2.3 MB/s eta 0:00:06
   - -------------------------------------- 0.4/12.9 MB 3.1 MB/s eta 0:00:05
   -- ------------------------------------- 0.8/12.9 MB 4.5 MB/s eta 0:00:03
   --- ------------------------------------ 1.3/12.9 MB 5.8 MB/s eta 0:00:02
   ----- ---------------------------------- 1.8/12.9 MB 6.8 MB/s eta 0:00:02
   ------- -------------------------------- 2.3/12.9 MB 7.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.9/12.9 MB 7.9 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.9 MB 8.2 MB/s eta 0:00:02
   --

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


 :numpy כעת נייבא את    

In [5]:
import numpy as np

<h3>np.array()</h3>

זהו מערך שעבורו מוגדרות פעולות נוספות מעבר למערך רגיל של פייתון. 

:בצורה הכי פשוטה אפשר פשוט להפוך רשימה רגילה של פייתון למערך כזה

In [21]:
simple_list = [1, 2, 3]
special_array = np.array(simple_list)

:אם נדפיס אותם הם לכאורה יראו אותו דבר בדיוק

In [22]:
print('list', simple_list)
print('array', special_array)

list [1, 2, 3]
array [1 2 3]


:נבדוק מה הסוג של כל אחד מהם

In [23]:
print('list', type(simple_list))
print('array', type(special_array))

list <class 'list'>
array <class 'numpy.ndarray'>


:בדיקת סוג הנתונים במערך

In [60]:
special_array.dtype

dtype('int32')

<h3>np.zeroz()</h3>

 .זוהי פונקציה היוצרת מערך מאותחל באפסים

In [24]:
new_array = np.zeros(10)
new_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

.חשוב לזכור!!! המערך יכול להכיל רק סוג אחד של נתונים בשונה מרשימה רגילה של פייתון

:יש דרך נוספת ליצור מערך ולמלא אותו באפסים

In [25]:
arr = np.empty(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<h3>np.ones()</h3>

:ניתן גם ליצור מערך של אחדות

In [26]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

np.full() ניתן ליצור מערך של כל מספר שנרצה ע"י הפונקציה 

In [47]:
fours = np.full(10, 4)
fours

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

:יצירת מערך של סדרת מספרים

In [119]:
array = np.arange(12, 20)
array

array([12, 13, 14, 15, 16, 17, 18, 19])

In [120]:
other_array = np.arange(30, 20, -3)
other_array

array([30, 27, 24, 21])

# מערך רב מימדי

In [48]:
two_dim = np.array([[1, 2, 3], [4, 5, 6], [5, 6, 7]])

In [49]:
three_dim = np.array([[[1, 2], [3, 4]],
                      [[5, 6], [7, 8]],
                      [[9, 10],[ 10, 11]]])

.בעצם כל פעם שאנחנו עוטפים בעוד סוגריים מרובעות , נוסף עוד מימד למערך

<h3> np.zeros() בחזרה לפונקציה </h3>

:בואו ננסה לשלוח אליה פרמטר של יותר ממיד אחד

In [50]:
try_zeros = np.zeros(2, 2)

TypeError: Cannot interpret '2' as a data type

!נופלת לנו שגיאה

:כאן חשוב להבין ולזכור


tuple כאשר אנו שולחים לה פרמטר של יותר ממימד אחד, נשלח אותו כ   

In [52]:
try_zeros = np.zeros((3, 2))
try_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# מציאת מספר המימדים של מערך

<h3> np.ndim() </h3>

In [55]:
np.ndim(try_zeros)

2

In [56]:
np.ndim(three_dim)

3

shape אם נרצה לקבל מידע יותר מפורט ממספר המימדים, נוכל להשתמש ב  

In [59]:
three_dim.shape

(3, 2, 2)

:וכדי לגלות את גודל המערך

In [64]:
three_dim.size

12

# יצירת מערכים עם ערכים אקראיים

מספרים אקראיים

In [68]:
random_float = np.random.rand()
random_float

0.1355482698063608

In [69]:
random_int = np.random.randint(10, 100)
random_int

87

מערכים אקראיים

In [72]:
random_array = np.random.rand(4, 4)
random_array

array([[0.73103847, 0.22293532, 0.5908581 , 0.56437102],
       [0.80790395, 0.56223602, 0.77451149, 0.29056381],
       [0.03866867, 0.61814278, 0.73290921, 0.34834887],
       [0.07205169, 0.53037733, 0.81727003, 0.89550009]])

In [73]:
random_int_array = np.random.randint(1, 10, size=(3, 3))
random_int_array

array([[3, 8, 7],
       [7, 5, 9],
       [7, 4, 1]])

# תרגילים

תרגיל 1: יצירת מערך ובדיקת תכונותיה

תיאור: צרי מערך של 10 מספרים שלמים באקראי בין 1 ל-50. בדקי את גודל המערך, סוג הנתונים ומספר הממדים שלו.

In [6]:
arr = np.random.randint(1,50,size=(1,10))
arr

array([[42, 47, 45, 12, 29, 41,  4,  5, 43, 20]], dtype=int32)

In [7]:
arr.size

10

In [8]:
arr.shape

(1, 10)

In [9]:
arr.dtype

dtype('int32')

תרגיל 2: יצירת מערך דו-ממדי

תיאור: צרי מערך דו-ממדי עם 2 שורות ו-5 עמודות של מספרים אקראיים בין 10 ל-100. בדקי את הצורה של המערך.

In [10]:
arr = np.random.randint(10,100,size=(2,5))
arr

array([[88, 81, 76, 88, 30],
       [23, 16, 35, 94, 53]], dtype=int32)

In [11]:
arr.shape

(2, 5)

# גישה לערכים ספציפיים במערך

In [85]:
num = three_dim[2][ 0][1]
num

10

In [86]:
num = three_dim[2, 0, 1]
num

10

:וכמו ברשימות רגילות אפשר לגשת גם מהסוף עם אינדקס שלילי

In [90]:
num = three_dim[-2][1][0]
num

7

In [91]:
three_dim

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [10, 11]]])

:אפשר לגשת למערך בעזרת תנאי בוליאני, וכך לקבל רק את מה שעונה על תנאי מסוים

In [117]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
condition = arr > 5
filtered_arr = arr[condition]
filtered_arr

array([ 6,  7,  8,  9, 10])

# numpy עיבוד נתונים עם 

:חיבור מערכים

In [93]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
ab = np.add(a, b)
ab

array([3, 4, 5])

In [94]:
ab = a + b
ab

array([3, 4, 5])

:חיסור מערכים

In [97]:
bc = np.subtract(a, b)
bc

array([-1,  0,  1])

In [98]:
bc = a - b
bc

array([-1,  0,  1])

:כפל מערכים

In [99]:
cd = np.multiply(a, b)
cd

array([2, 4, 6])

In [100]:
cd = a * b
cd

array([2, 4, 6])

In [101]:
de = a ** b
de

array([1, 4, 9])

:חילוק מערכים

In [102]:
ef = np.divide(a, b)
ef

array([0.5, 1. , 1.5])

In [103]:
ef = a / b
ef

array([0.5, 1. , 1.5])

# שינוי צורה של מערך

In [122]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6]])

!חשוב להקפיד לשים לב שמספר האלמנטים חייב להיות זהה ב2 הצורות

# פונקציות אוניברסליות

: חישוב שורש ריבועי לכל אלמנט

In [105]:
after_sqrt = np.sqrt(de)
after_sqrt

array([1., 2., 3.])

: n העלאת כל אלמנט בחזקת

In [107]:
power = np.power(de, 2)
power

array([ 1, 16, 81], dtype=int32)

מציאת מינימום :

In [108]:
power.min()

1

:מציאת מקסימום

In [111]:
power.max()

81

:מציאת סכום

In [112]:
np.sum(power)

98

:מציאת ממוצע

In [114]:
np.mean(power)

32.666666666666664

:מציאת חציון

In [115]:
np.median(power)

16.0

:מציאת סטיית התקן

In [116]:
np.std(power)

34.721111093332766

# תרגילים

1. צרי מערך באורך 10 של מספרים שלמים רנדומליים בין 1 ל-50 וחשבי את הממוצע של המספרים

In [13]:
arr = np.random.randint(1,50,size=(1,10))
arr


array([[ 4, 34, 14, 34, 38, 27,  6, 13, 31, 31]], dtype=int32)

In [14]:
np.mean(arr)

np.float64(23.2)

2. צרי שני מערכים דו מימדיים בגודל 3, חברי אותם, ובדקי מה הממוצע של התוצאה

In [15]:
arr1 = np.random.randint(1,50,size=(2,3))
arr2 = np.random.randint(1,50,size=(2,3))
result =  np.add(arr1, arr2)
result

array([[52, 65, 33],
       [36, 36, 39]], dtype=int32)

In [16]:
np.mean(result)

np.float64(43.5)

3. צרי מערך של 20 מספרים שלמים רנדומליים בין 1 ל-100. מצאי את כל המספרים שגדולים מ-50 במערך זה.

In [17]:
arr4 = np.random.randint(1,100,size=(1,20))
arr4


array([[69, 40, 68,  7, 66, 25, 18, 44,  7, 83, 80, 66, 21, 53, 57, 95,
        18, 93, 84, 74]], dtype=int32)

In [18]:
a = arr>50
a

array([[False, False, False, False, False, False, False, False, False,
        False]])

In [20]:
a = arr4>50
a

array([[ True, False,  True, False,  True, False, False, False, False,
         True,  True,  True, False,  True,  True,  True, False,  True,
         True,  True]])

In [21]:
a = arr4>50
new = arr4[a]
new

array([69, 68, 66, 83, 80, 66, 53, 57, 95, 93, 84, 74], dtype=int32)

4. צרי מערך של מספרים מ-1 עד 10. ערבבי את המערך ולאחר מכן בחרי באופן אקראי  אלמנטים ממנו 

# !בהצלחה